formatter: markdown table

output:
  file: README.md
  mode: inject

sections:
  show:
  - header
  - inputs
  - outputs
  - providers
  - resources

sort:
  enabled: true
  by: name

settings:
  anchor: true
  escape: false
  indent: 2
  required: true
  sensitive: true
